// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormFocusController from "./form_focus_controller"
application.register("form-focus", FormFocusController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
